apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeplay-services
spec:
  syncPolicy:
    syncOptions:
    - PruneLast=true
  project: default
  source:
    repoURL: https://github.com/simeonstoykovqc/kubeplay-argo
    targetRevision: blue-green-v2-services
    path: charts/app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc 
    namespace: default
