release: blue 
applications:
- toLoad: class5
- toLoad: class0,class1,class3,class4,class6,class7,class10
- toLoad: class2,class8,class9,class11
redeployApplication: 1883614123123
redeployRouter: 1883614123123

