{{- range $index, $application := .Values.applications }}

{{- $classes := splitList "," .toLoad }}
{{- $classLength := add -1 (len $classes) }}
{{- range $cindex, $class := $classes }}

---
apiVersion: v1
kind: Service
metadata:
  name: kubeplay-application-{{ $class }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    {{ $class }}: "can-serve"
    deployVersion: {{ $.Values.release }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
{{- end }}
{{- end }}

