apiVersion: v1
kind: Service
metadata:
  name: kubeplay-router
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: kubeplay-router-{{ .Values.release }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
