apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application
spec:
  source:
    repoURL: http://<repository-url>
    targetRevision: HEAD 
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default

